create extension if not exists pgcrypto;

do $$ begin create type integration_kind as enum ('github','supabase','render','sentry','linear','semrush','ahrefs','dataforseo'); exception when duplicate_object then null; end $$;
do $$ begin create type scan_status as enum ('queued','running','done','failed'); exception when duplicate_object then null; end $$;

create table if not exists public.users_meta (user_id uuid primary key references auth.users(id) on delete cascade, wrapped_dek bytea not null, created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade);
create table if not exists public.dashboards (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null check (length(name) between 1 and 120), url text not null, notes text);
create table if not exists public.dashboard_credentials (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, dashboard_id uuid not null references public.dashboards(id) on delete cascade, ciphertext text not null, iv text not null, wrapped_dek text not null, login_url text not null, success_selector text not null);
create table if not exists public.integrations (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, dashboard_id uuid not null references public.dashboards(id) on delete cascade, kind integration_kind not null, ciphertext text not null, iv text not null, wrapped_dek text not null, metadata jsonb not null default '{}'::jsonb);
create table if not exists public.scan_jobs (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, dashboard_id uuid not null references public.dashboards(id) on delete cascade, status scan_status not null default 'queued', progress jsonb not null default '{"stage":"queued","percent":0}'::jsonb, error_log jsonb not null default '[]'::jsonb, started_at timestamptz, finished_at timestamptz);
create table if not exists public.scans (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, job_id uuid not null unique references public.scan_jobs(id) on delete cascade, summary jsonb not null default '{}'::jsonb, scores jsonb not null default '{}'::jsonb);
create table if not exists public.findings (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, scan_id uuid not null references public.scans(id) on delete cascade, dimension text not null, severity text not null check (severity in ('P0','P1','P2','P3')), title text not null, description_md text not null, evidence jsonb not null check (jsonb_typeof(evidence) = 'array' and jsonb_array_length(evidence) > 0), recommendation_md text not null, effort int not null default 1, impact int not null default 1);
create table if not exists public.competitors (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, scan_id uuid not null references public.scans(id) on delete cascade, name text not null, url text not null, source text not null, feature_matrix jsonb not null default '{}'::jsonb, semrush_data jsonb, ahrefs_data jsonb, dataforseo_data jsonb);
create table if not exists public.artifacts (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, scan_id uuid not null references public.scans(id) on delete cascade, kind text not null, storage_path text not null, meta jsonb not null default '{}'::jsonb);
create table if not exists public.audit_log (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, actor_id uuid not null references auth.users(id) on delete cascade, action text not null, target text not null, meta jsonb not null default '{}'::jsonb);
create table if not exists public.memory_notes (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), owner_id uuid not null references auth.users(id) on delete cascade, dashboard_id uuid not null references public.dashboards(id) on delete cascade, kind text not null, content text not null, source_scan_id uuid references public.scans(id) on delete set null);
